//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AM2RLauncher.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AM2RLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] AM2RIcon {
            get {
                object obj = ResourceManager.GetObject("AM2RIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] bgCentered {
            get {
                object obj = ResourceManager.GetObject("bgCentered", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] discordIcon48 {
            get {
                object obj = ResourceManager.GetObject("discordIcon48", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] githubIcon48 {
            get {
                object obj = ResourceManager.GetObject("githubIcon48", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] redditIcon48 {
            get {
                object obj = ResourceManager.GetObject("redditIcon48", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] youtubeIcon48 {
            get {
                object obj = ResourceManager.GetObject("youtubeIcon48", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] matrixIcon48 {
            get {
                object obj = ResourceManager.GetObject("matrixIcon48", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
