//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AM2RLauncher.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AM2RLauncher.Language.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABORT.
        /// </summary>
        public static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD NEW MOD.
        /// </summary>
        public static string AddNewMod {
            get {
                return ResourceManager.GetString("AddNewMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a mod to be installed..
        /// </summary>
        public static string AddNewModToolTip {
            get {
                return ResourceManager.GetString("AddNewModToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create an APK..
        /// </summary>
        public static string ApkButtonDisabledToolTip {
            get {
                return ResourceManager.GetString("ApkButtonDisabledToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an APK for .
        /// </summary>
        public static string ApkButtonEnabledToolTip {
            get {
                return ResourceManager.GetString("ApkButtonEnabledToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an archive of a previously installed Community Update. It cannot be re-installed and will remove itself if its game files are deleted. It shares saves with the currently installed Community Updates, so be sure to create a backup of your saves before running this profile!.
        /// </summary>
        public static string ArchiveNotes {
            get {
                return ResourceManager.GetString("ArchiveNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author(s):.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically update AM2R and the AM2RLauncher.
        /// </summary>
        public static string AutoUpdate {
            get {
                return ResourceManager.GetString("AutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog.
        /// </summary>
        public static string ChangelogTab {
            get {
                return ResourceManager.GetString("ChangelogTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel this now? This will delete all your progress!.
        /// </summary>
        public static string CloseOnCloningText {
            get {
                return ResourceManager.GetString("CloseOnCloningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you can&apos;t close this while it&apos;s installing! Please wait until it&apos;s finished..
        /// </summary>
        public static string CloseOnInstallingText {
            get {
                return ResourceManager.GetString("CloseOnInstallingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem with your Patchdata folder. It has been deleted, please download it again..
        /// </summary>
        public static string CorruptPatchData {
            get {
                return ResourceManager.GetString("CorruptPatchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE APK.
        /// </summary>
        public static string CreateAPK {
            get {
                return ResourceManager.GetString("CreateAPK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATING APK.
        /// </summary>
        public static string CreatingAPK {
            get {
                return ResourceManager.GetString("CreatingAPK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current profile:.
        /// </summary>
        public static string CurrentProfile {
            get {
                return ResourceManager.GetString("CurrentProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter custom game environment variables:.
        /// </summary>
        public static string CustomEnvVarLabel {
            get {
                return ResourceManager.GetString("CustomEnvVarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use custom download mirror.
        /// </summary>
        public static string CustomMirrorCheck {
            get {
                return ResourceManager.GetString("CustomMirrorCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $NAME couldn&apos;t be deleted..
        /// </summary>
        public static string DeleteModButtonCantDelete {
            get {
                return ResourceManager.GetString("DeleteModButtonCantDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $NAME was successfully deleted!.
        /// </summary>
        public static string DeleteModButtonSuccess {
            get {
                return ResourceManager.GetString("DeleteModButtonSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE MOD.
        /// </summary>
        public static string DeleteModButtonText {
            get {
                return ResourceManager.GetString("DeleteModButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete $NAME..
        /// </summary>
        public static string DeleteModButtonToolTip {
            get {
                return ResourceManager.GetString("DeleteModButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete all files for $NAME. Are you sure you want to continue?.
        /// </summary>
        public static string DeleteModWarning {
            get {
                return ResourceManager.GetString("DeleteModWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Official AM2R Discord.
        /// </summary>
        public static string DiscordToolTip {
            get {
                return ResourceManager.GetString("DiscordToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWNLOAD.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWNLOADING.
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download source:.
        /// </summary>
        public static string DownloadSource {
            get {
                return ResourceManager.GetString("DownloadSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorWindowTitle {
            get {
                return ResourceManager.GetString("ErrorWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Community-Developers Github Page.
        /// </summary>
        public static string GithubToolTip {
            get {
                return ResourceManager.GetString("GithubToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use high quality music when patching to Android.
        /// </summary>
        public static string HighQualityAndroid {
            get {
                return ResourceManager.GetString("HighQualityAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use high quality music when patching to PC.
        /// </summary>
        public static string HighQualityPC {
            get {
                return ResourceManager.GetString("HighQualityPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTALL.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTALLING.
        /// </summary>
        public static string Installing {
            get {
                return ResourceManager.GetString("Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t establish an internet connection! Try again later!.
        /// </summary>
        public static string InternetConnectionDrop {
            get {
                return ResourceManager.GetString("InternetConnectionDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java not found! Cannot generate an APK without a Java installation. Please make sure that Java is installed and added to PATH..
        /// </summary>
        public static string JavaNotFound {
            get {
                return ResourceManager.GetString("JavaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher Language: (requires restart to take effect).
        /// </summary>
        public static string LanguageNotice {
            get {
                return ResourceManager.GetString("LanguageNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string LauncherSettingsTab {
            get {
                return ResourceManager.GetString("LauncherSettingsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub (Primary).
        /// </summary>
        public static string MirrorGithubText {
            get {
                return ResourceManager.GetString("MirrorGithubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitLab (Mirror).
        /// </summary>
        public static string MirrorGitlabText {
            get {
                return ResourceManager.GetString("MirrorGitlabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $NAME is already installed!.
        /// </summary>
        public static string ModIsAlreadyInstalledMessage {
            get {
                return ResourceManager.GetString("ModIsAlreadyInstalledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $NAME cannot be installed! It&apos;s for $OS. Download the $CURRENTOS version instead if it exists, or ask the mod authors to make one..
        /// </summary>
        public static string ModIsForWrongOS {
            get {
                return ResourceManager.GetString("ModIsForWrongOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $NAME is an invalid AM2R mod!.
        /// </summary>
        public static string ModIsInvalidMessage {
            get {
                return ResourceManager.GetString("ModIsInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $NAME was successfully added! Go to the Play Tab in order to install it!.
        /// </summary>
        public static string ModSuccessfullyInstalledMessage {
            get {
                return ResourceManager.GetString("ModSuccessfullyInstalledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string NewsTab {
            get {
                return ResourceManager.GetString("NewsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t establish an internet connection! You can still play the game, but updates will not occur until the launcher is restarted and can connect to the internet..
        /// </summary>
        public static string NoInternetConnection {
            get {
                return ResourceManager.GetString("NoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPEN PROFILE SAVE FOLDER.
        /// </summary>
        public static string OpenSaveFolder {
            get {
                return ResourceManager.GetString("OpenSaveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the Folder where save files are located for $NAME..
        /// </summary>
        public static string OpenSaveFolderToolTip {
            get {
                return ResourceManager.GetString("OpenSaveFolderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAY.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently downloading . . ..
        /// </summary>
        public static string PlayButtonDownladingToolTip {
            get {
                return ResourceManager.GetString("PlayButtonDownladingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the necessary patch files..
        /// </summary>
        public static string PlayButtonDownloadToolTip {
            get {
                return ResourceManager.GetString("PlayButtonDownloadToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently installing. . ..
        /// </summary>
        public static string PlayButtonInstallingToolTip {
            get {
                return ResourceManager.GetString("PlayButtonInstallingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install .
        /// </summary>
        public static string PlayButtonInstallToolTip {
            get {
                return ResourceManager.GetString("PlayButtonInstallToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently already playing!.
        /// </summary>
        public static string PlayButtonPlayingToolTip {
            get {
                return ResourceManager.GetString("PlayButtonPlayingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play .
        /// </summary>
        public static string PlayButtonPlayToolTip {
            get {
                return ResourceManager.GetString("PlayButtonPlayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your AM2R_1.1.zip.
        /// </summary>
        public static string PlayButtonSelect11ToolTip {
            get {
                return ResourceManager.GetString("PlayButtonSelect11ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAYING.
        /// </summary>
        public static string Playing {
            get {
                return ResourceManager.GetString("Playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string PlayTab {
            get {
                return ResourceManager.GetString("PlayTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create game debug logs.
        /// </summary>
        public static string ProfileDebugCheckBox {
            get {
                return ResourceManager.GetString("ProfileDebugCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile notes:
        ///.
        /// </summary>
        public static string ProfileNotes {
            get {
                return ResourceManager.GetString("ProfileNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Settings.
        /// </summary>
        public static string ProfileSettingsTab {
            get {
                return ResourceManager.GetString("ProfileSettingsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress: .
        /// </summary>
        public static string ProgressbarProgress {
            get {
                return ResourceManager.GetString("ProgressbarProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Official AM2R Subreddit.
        /// </summary>
        public static string RedditToolTip {
            get {
                return ResourceManager.GetString("RedditToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: This profile uses the default save location! This could corrupt your save data - please ensure that you have made a backup..
        /// </summary>
        public static string SaveLocationWarning {
            get {
                return ResourceManager.GetString("SaveLocationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT AM2R_1.1.zip.
        /// </summary>
        public static string Select11 {
            get {
                return ResourceManager.GetString("Select11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select AM2R_1.1.zip.
        /// </summary>
        public static string Select11FileDialog {
            get {
                return ResourceManager.GetString("Select11FileDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your Mod.
        /// </summary>
        public static string SelectModFileDialog {
            get {
                return ResourceManager.GetString("SelectModFileDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string SuccessWindowTitle {
            get {
                return ResourceManager.GetString("SuccessWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Language.
        /// </summary>
        public static string SystemLanguage {
            get {
                return ResourceManager.GetString("SystemLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Launcher.
        /// </summary>
        public static string TrayButtonShow {
            get {
                return ResourceManager.GetString("TrayButtonShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t access the Folder in order to download the update! Consider moving the program, or disabling auto-updates..
        /// </summary>
        public static string UnauthorizedAccessMessage {
            get {
                return ResourceManager.GetString("UnauthorizedAccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Exception has occured in your Application..
        /// </summary>
        public static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Mod Update.
        /// </summary>
        public static string UpdateMod {
            get {
                return ResourceManager.GetString("UpdateMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE MOD.
        /// </summary>
        public static string UpdateModButtonText {
            get {
                return ResourceManager.GetString("UpdateModButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a zip to update $NAME..
        /// </summary>
        public static string UpdateModButtonToolTip {
            get {
                return ResourceManager.GetString("UpdateModButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t update $NAME with $SELECT. Add $SELECT as a new mod instead!.
        /// </summary>
        public static string UpdateModButtonWrongMod {
            get {
                return ResourceManager.GetString("UpdateModButtonWrongMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will replace all files for $NAME with the selected new version. Are you sure you want to continue?.
        /// </summary>
        public static string UpdateModWarning {
            get {
                return ResourceManager.GetString("UpdateModWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string VersionLabel {
            get {
                return ResourceManager.GetString("VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string WarningWindowOk {
            get {
                return ResourceManager.GetString("WarningWindowOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AM2RLauncher can NOT validate custom mirror links.
        ///
        ///If somebody is telling you to paste a link in this field, they may be trying to infect your computer.
        ///
        ///Proceed with caution..
        /// </summary>
        public static string WarningWindowText {
            get {
                return ResourceManager.GetString("WarningWindowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING.
        /// </summary>
        public static string WarningWindowTitle {
            get {
                return ResourceManager.GetString("WarningWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xdelta not found! Cannot install Profiles without it. Please install xdelta3 from your local package manager..
        /// </summary>
        public static string XdeltaNotFound {
            get {
                return ResourceManager.GetString("XdeltaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Community-Developers YouTube Channel.
        /// </summary>
        public static string YoutubeToolTip {
            get {
                return ResourceManager.GetString("YoutubeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Archives (*.zip).
        /// </summary>
        public static string ZipArchiveText {
            get {
                return ResourceManager.GetString("ZipArchiveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected Zip is not AM2R 1.1! Please choose another Zip file..
        /// </summary>
        public static string ZipIsNotAM2R11 {
            get {
                return ResourceManager.GetString("ZipIsNotAM2R11", resourceCulture);
            }
        }
    }
}
