//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AM2RLauncher.Language {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AM2RLauncher.Language.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        public static string AddNewMod {
            get {
                return ResourceManager.GetString("AddNewMod", resourceCulture);
            }
        }
        
        public static string AddNewModToolTip {
            get {
                return ResourceManager.GetString("AddNewModToolTip", resourceCulture);
            }
        }
        
        public static string ApkButtonDisabledToolTip {
            get {
                return ResourceManager.GetString("ApkButtonDisabledToolTip", resourceCulture);
            }
        }
        
        public static string ApkButtonEnabledToolTip {
            get {
                return ResourceManager.GetString("ApkButtonEnabledToolTip", resourceCulture);
            }
        }
        
        public static string ArchiveNotesCommunityUpdates {
            get {
                return ResourceManager.GetString("ArchiveNotesCommunityUpdates", resourceCulture);
            }
        }
        
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        public static string AutoUpdateAM2R {
            get {
                return ResourceManager.GetString("AutoUpdateAM2R", resourceCulture);
            }
        }
        
        public static string AutoUpdateLauncher {
            get {
                return ResourceManager.GetString("AutoUpdateLauncher", resourceCulture);
            }
        }
        
        public static string ChangelogTab {
            get {
                return ResourceManager.GetString("ChangelogTab", resourceCulture);
            }
        }
        
        public static string CloseOnCloningText {
            get {
                return ResourceManager.GetString("CloseOnCloningText", resourceCulture);
            }
        }
        
        public static string CloseOnInstallingText {
            get {
                return ResourceManager.GetString("CloseOnInstallingText", resourceCulture);
            }
        }
        
        public static string CorruptPatchData {
            get {
                return ResourceManager.GetString("CorruptPatchData", resourceCulture);
            }
        }
        
        public static string CreateAPK {
            get {
                return ResourceManager.GetString("CreateAPK", resourceCulture);
            }
        }
        
        public static string CreatingAPK {
            get {
                return ResourceManager.GetString("CreatingAPK", resourceCulture);
            }
        }
        
        public static string CurrentProfile {
            get {
                return ResourceManager.GetString("CurrentProfile", resourceCulture);
            }
        }
        
        public static string CustomEnvVarLabel {
            get {
                return ResourceManager.GetString("CustomEnvVarLabel", resourceCulture);
            }
        }
        
        public static string CustomMirrorCheck {
            get {
                return ResourceManager.GetString("CustomMirrorCheck", resourceCulture);
            }
        }
        
        public static string DeleteModButtonCantDelete {
            get {
                return ResourceManager.GetString("DeleteModButtonCantDelete", resourceCulture);
            }
        }
        
        public static string DeleteModButtonSuccess {
            get {
                return ResourceManager.GetString("DeleteModButtonSuccess", resourceCulture);
            }
        }
        
        public static string DeleteModButtonText {
            get {
                return ResourceManager.GetString("DeleteModButtonText", resourceCulture);
            }
        }
        
        public static string DeleteModButtonToolTip {
            get {
                return ResourceManager.GetString("DeleteModButtonToolTip", resourceCulture);
            }
        }
        
        public static string DeleteModWarning {
            get {
                return ResourceManager.GetString("DeleteModWarning", resourceCulture);
            }
        }
        
        public static string DiscordToolTip {
            get {
                return ResourceManager.GetString("DiscordToolTip", resourceCulture);
            }
        }
        
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        public static string DownloadSource {
            get {
                return ResourceManager.GetString("DownloadSource", resourceCulture);
            }
        }
        
        public static string ErrorWindowTitle {
            get {
                return ResourceManager.GetString("ErrorWindowTitle", resourceCulture);
            }
        }
        
        public static string GithubToolTip {
            get {
                return ResourceManager.GetString("GithubToolTip", resourceCulture);
            }
        }
        
        public static string HighQualityAndroid {
            get {
                return ResourceManager.GetString("HighQualityAndroid", resourceCulture);
            }
        }
        
        public static string HighQualityPC {
            get {
                return ResourceManager.GetString("HighQualityPC", resourceCulture);
            }
        }
        
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        public static string Installing {
            get {
                return ResourceManager.GetString("Installing", resourceCulture);
            }
        }
        
        public static string InternetConnectionDrop {
            get {
                return ResourceManager.GetString("InternetConnectionDrop", resourceCulture);
            }
        }
        
        public static string InvalidGitURL {
            get {
                return ResourceManager.GetString("InvalidGitURL", resourceCulture);
            }
        }
        
        public static string JavaNotFound {
            get {
                return ResourceManager.GetString("JavaNotFound", resourceCulture);
            }
        }
        
        public static string LanguageNotice {
            get {
                return ResourceManager.GetString("LanguageNotice", resourceCulture);
            }
        }
        
        public static string LauncherSettingsTab {
            get {
                return ResourceManager.GetString("LauncherSettingsTab", resourceCulture);
            }
        }
        
        public static string MirrorGithubText {
            get {
                return ResourceManager.GetString("MirrorGithubText", resourceCulture);
            }
        }
        
        public static string MirrorGitlabText {
            get {
                return ResourceManager.GetString("MirrorGitlabText", resourceCulture);
            }
        }
        
        public static string ModIsAlreadyInstalledMessage {
            get {
                return ResourceManager.GetString("ModIsAlreadyInstalledMessage", resourceCulture);
            }
        }
        
        public static string ModIsForWrongOS {
            get {
                return ResourceManager.GetString("ModIsForWrongOS", resourceCulture);
            }
        }
        
        public static string ModIsInvalidMessage {
            get {
                return ResourceManager.GetString("ModIsInvalidMessage", resourceCulture);
            }
        }
        
        public static string ModSuccessfullyInstalledMessage {
            get {
                return ResourceManager.GetString("ModSuccessfullyInstalledMessage", resourceCulture);
            }
        }
        
        public static string NewsTab {
            get {
                return ResourceManager.GetString("NewsTab", resourceCulture);
            }
        }
        
        public static string NoInternetConnection {
            get {
                return ResourceManager.GetString("NoInternetConnection", resourceCulture);
            }
        }
        
        public static string OpenProfileFolder {
            get {
                return ResourceManager.GetString("OpenProfileFolder", resourceCulture);
            }
        }
        
        public static string OpenProfileFolderToolTip {
            get {
                return ResourceManager.GetString("OpenProfileFolderToolTip", resourceCulture);
            }
        }
        
        public static string OpenSaveFolder {
            get {
                return ResourceManager.GetString("OpenSaveFolder", resourceCulture);
            }
        }
        
        public static string OpenSaveFolderToolTip {
            get {
                return ResourceManager.GetString("OpenSaveFolderToolTip", resourceCulture);
            }
        }
        
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        public static string PlayButtonDownladingToolTip {
            get {
                return ResourceManager.GetString("PlayButtonDownladingToolTip", resourceCulture);
            }
        }
        
        public static string PlayButtonDownloadToolTip {
            get {
                return ResourceManager.GetString("PlayButtonDownloadToolTip", resourceCulture);
            }
        }
        
        public static string PlayButtonInstallingToolTip {
            get {
                return ResourceManager.GetString("PlayButtonInstallingToolTip", resourceCulture);
            }
        }
        
        public static string PlayButtonInstallToolTip {
            get {
                return ResourceManager.GetString("PlayButtonInstallToolTip", resourceCulture);
            }
        }
        
        public static string PlayButtonPlayingToolTip {
            get {
                return ResourceManager.GetString("PlayButtonPlayingToolTip", resourceCulture);
            }
        }
        
        public static string PlayButtonPlayToolTip {
            get {
                return ResourceManager.GetString("PlayButtonPlayToolTip", resourceCulture);
            }
        }
        
        public static string PlayButtonSelect11ToolTip {
            get {
                return ResourceManager.GetString("PlayButtonSelect11ToolTip", resourceCulture);
            }
        }
        
        public static string Playing {
            get {
                return ResourceManager.GetString("Playing", resourceCulture);
            }
        }
        
        public static string PlayTab {
            get {
                return ResourceManager.GetString("PlayTab", resourceCulture);
            }
        }
        
        public static string ProfileDebugCheckBox {
            get {
                return ResourceManager.GetString("ProfileDebugCheckBox", resourceCulture);
            }
        }
        
        public static string ProfileNotes {
            get {
                return ResourceManager.GetString("ProfileNotes", resourceCulture);
            }
        }
        
        public static string ProfileSettingsTab {
            get {
                return ResourceManager.GetString("ProfileSettingsTab", resourceCulture);
            }
        }
        
        public static string ProgressbarProgress {
            get {
                return ResourceManager.GetString("ProgressbarProgress", resourceCulture);
            }
        }
        
        public static string RedditToolTip {
            get {
                return ResourceManager.GetString("RedditToolTip", resourceCulture);
            }
        }
        
        public static string SaveLocationWarning {
            get {
                return ResourceManager.GetString("SaveLocationWarning", resourceCulture);
            }
        }
        
        public static string Select11 {
            get {
                return ResourceManager.GetString("Select11", resourceCulture);
            }
        }
        
        public static string Select11FileDialog {
            get {
                return ResourceManager.GetString("Select11FileDialog", resourceCulture);
            }
        }
        
        public static string SelectModFileDialog {
            get {
                return ResourceManager.GetString("SelectModFileDialog", resourceCulture);
            }
        }
        
        public static string SuccessWindowTitle {
            get {
                return ResourceManager.GetString("SuccessWindowTitle", resourceCulture);
            }
        }
        
        public static string SystemLanguage {
            get {
                return ResourceManager.GetString("SystemLanguage", resourceCulture);
            }
        }
        
        public static string TrayButtonShow {
            get {
                return ResourceManager.GetString("TrayButtonShow", resourceCulture);
            }
        }
        
        public static string UnauthorizedAccessMessage {
            get {
                return ResourceManager.GetString("UnauthorizedAccessMessage", resourceCulture);
            }
        }
        
        public static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        public static string UpdateMod {
            get {
                return ResourceManager.GetString("UpdateMod", resourceCulture);
            }
        }
        
        public static string UpdateModButtonText {
            get {
                return ResourceManager.GetString("UpdateModButtonText", resourceCulture);
            }
        }
        
        public static string UpdateModButtonToolTip {
            get {
                return ResourceManager.GetString("UpdateModButtonToolTip", resourceCulture);
            }
        }
        
        public static string UpdateModButtonWrongMod {
            get {
                return ResourceManager.GetString("UpdateModButtonWrongMod", resourceCulture);
            }
        }
        
        public static string UpdateModWarning {
            get {
                return ResourceManager.GetString("UpdateModWarning", resourceCulture);
            }
        }
        
        public static string VersionLabel {
            get {
                return ResourceManager.GetString("VersionLabel", resourceCulture);
            }
        }
        
        public static string WarningWindowOk {
            get {
                return ResourceManager.GetString("WarningWindowOk", resourceCulture);
            }
        }
        
        public static string WarningWindowText {
            get {
                return ResourceManager.GetString("WarningWindowText", resourceCulture);
            }
        }
        
        public static string WarningWindowTitle {
            get {
                return ResourceManager.GetString("WarningWindowTitle", resourceCulture);
            }
        }
        
        public static string XdeltaNotFound {
            get {
                return ResourceManager.GetString("XdeltaNotFound", resourceCulture);
            }
        }
        
        public static string YoutubeToolTip {
            get {
                return ResourceManager.GetString("YoutubeToolTip", resourceCulture);
            }
        }
        
        public static string ZipArchiveText {
            get {
                return ResourceManager.GetString("ZipArchiveText", resourceCulture);
            }
        }
        
        public static string ZipIsNotAM2R11 {
            get {
                return ResourceManager.GetString("ZipIsNotAM2R11", resourceCulture);
            }
        }
        
        public static string ArchiveMod {
            get {
                return ResourceManager.GetString("ArchiveMod", resourceCulture);
            }
        }
        
        public static string ArchiveNotesMods {
            get {
                return ResourceManager.GetString("ArchiveNotesMods", resourceCulture);
            }
        }
    }
}
