blank_issues_enabled: false
contact_links:
  - name: AM2R-FAQ
    url: https://am2r-community-developers.github.io/DistributionCenter/faq.html
    about: Find frequently asked questions for AM2R.
  - name: AM2R Issues
    url: https://github.com/AM2R-Community-Developers/AM2R-Community-Updates/issues/new/choose
    about: Got an issue for AM2R itself?
  - name: AM2RLauncher Wiki
    url: https://github.com/AM2R-Community-Developers/AM2RLauncher/wiki
    about: A more in-depth documentation for features and usage of the AM2RLauncher.
