name: Build And Publish

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        configuration: [Release]
        include:
          - os: ubuntu-latest
            COMMAND: AM2RLauncher.Gtk -p:PublishSingleFile=true -p:DebugType=embedded -r ubuntu.18.04-x64 --no-self-contained -o builds/ubuntu-latest
            ARTIFACT: AM2RLauncher/builds/ubuntu-latest
          - os: macOS-latest
            COMMAND: AM2RLauncher.Mac -r osx-x64 --no-self-contained -o builds/macOS-latest
            ARTIFACT: AM2RLauncher/builds/macOS-latest
          - os: windows-latest
            COMMAND: AM2RLauncher.Wpf -r win-x86 
            ARTIFACT: AM2RLauncher\AM2RLauncher.Wpf\bin\Release\net48\win-x86\
    runs-on: ${{ matrix.os }}
    

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./AM2RLauncher
      run: dotnet restore
    - name: Build
      working-directory: ./AM2RLauncher
      run: dotnet publish ${{ matrix.COMMAND }} -c "${{ matrix.configuration }}"
    - name: Post-Build
      run: cp ./LICENSE ./${{ matrix.ARTIFACT }}/
    # Steps for uploading artifacts.
    - name: Zip to Archive
      run: 7z a -tzip ${{ matrix.os }}.zip ./${{ matrix.ARTIFACT }}
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ${{ matrix.os }}
        path: ${{ matrix.os }}.zip
